# Generated by Django 4.2.7 on 2023-11-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff_details",
            name="cl1_bal",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
