# Generated by Django 4.2.7 on 2023-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_alter_staff_details_cl1_bal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff_details",
            name="DL_bal",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="staff_details",
            name="LoP",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="staff_details",
            name="ML_bal",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="staff_details",
            name="VL_bal",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="staff_details",
            name="cl2_bal",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="staff_details",
            name="comp_off",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
