# Generated by Django 4.2.7 on 2024-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0004_remove_leave_application_alt_assigned_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternatearrangements",
            name="time_of_request",
            field=models.DateTimeField(null=True),
        ),
    ]
