# Generated by Django 4.2.7 on 2024-02-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0005_alternatearrangements_time_of_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave_application",
            name="alt_linways_assigned",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
