# Generated by Django 4.2.7 on 2024-02-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0006_leave_application_alt_linways_assigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternatearrangements",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
