# Generated by Django 4.2.7 on 2024-02-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0007_alternatearrangements_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alternatearrangements",
            name="alt_class_sem",
        ),
        migrations.RemoveField(
            model_name="alternatearrangements",
            name="alt_linways_assigned",
        ),
        migrations.RemoveField(
            model_name="alternatearrangements",
            name="alt_subject",
        ),
        migrations.RemoveField(
            model_name="alternatearrangements",
            name="date",
        ),
        migrations.RemoveField(
            model_name="alternatearrangements",
            name="employee_id",
        ),
        migrations.RemoveField(
            model_name="alternatearrangements",
            name="time_of_request",
        ),
        migrations.AddField(
            model_name="alternatearrangements",
            name="alt_class",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="alternatearrangements",
            name="alt_semester",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
