# Generated by Django 4.2.7 on 2024-02-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0011_alternatearrangements_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status_leave_application",
            name="alt_hour",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="status_leave_application",
            name="alt_linways_assigned",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="status_leave_application",
            name="alt_subject",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
