# Generated by Django 4.2.7 on 2024-02-08 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0012_alter_status_leave_application_alt_hour_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status_leave_application",
            name="alt_assigned_teacher",
        ),
        migrations.RemoveField(
            model_name="status_leave_application",
            name="alt_class_sem",
        ),
        migrations.RemoveField(
            model_name="status_leave_application",
            name="alt_hour",
        ),
        migrations.RemoveField(
            model_name="status_leave_application",
            name="alt_linways_assigned",
        ),
        migrations.RemoveField(
            model_name="status_leave_application",
            name="alt_subject",
        ),
    ]
