# Generated by Django 4.2.7 on 2024-02-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0013_remove_status_leave_application_alt_assigned_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternatearrangements",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
    ]
