# Generated by Django 4.2.7 on 2024-02-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0014_alternatearrangements_submitted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alternatearrangements",
            name="submitted",
        ),
        migrations.AddField(
            model_name="leave_application",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
    ]
