# Generated by Django 4.2.7 on 2024-02-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0015_remove_alternatearrangements_submitted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pdf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdffile", models.FileField(upload_to="media/")),
            ],
        ),
    ]
