# Generated by Django 4.2.7 on 2024-02-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0020_rename_nature_of_leavee_pdf_nature_of_leave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff_details",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
