# Generated by Django 4.2.7 on 2024-04-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0022_delete_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status_leave_application",
            name="status_of_request",
            field=models.CharField(default="", max_length=100),
        ),
    ]
