# Generated by Django 4.2.7 on 2024-03-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Duty_Leave_Certificate_Pdf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=10, null=True)),
                ("nature_of_leave", models.CharField(max_length=10, null=True)),
                ("leave_id", models.IntegerField(null=True)),
                ("pdffile", models.FileField(upload_to="media/")),
            ],
        ),
        migrations.CreateModel(
            name="Medical_Certificate_Pdf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=10, null=True)),
                ("nature_of_leave", models.CharField(max_length=10, null=True)),
                ("leave_id", models.IntegerField(null=True)),
                ("pdffile", models.FileField(upload_to="media/")),
            ],
        ),
    ]
