# Generated by Django 4.2.7 on 2024-03-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_duty_leave_certificate_pdf_medical_certificate_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="duty_leave_certificate_pdf",
            name="leave_from",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="medical_certificate_pdf",
            name="leave_from",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="duty_leave_certificate_pdf",
            name="pdffile",
            field=models.FileField(upload_to="dutyLeave/"),
        ),
        migrations.AlterField(
            model_name="medical_certificate_pdf",
            name="pdffile",
            field=models.FileField(upload_to="medicalLeave/"),
        ),
    ]
