# Generated by Django 4.2.7 on 2024-04-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0003_duty_leave_certificate_pdf_leave_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave_application_hr",
            name="status_of_request",
            field=models.CharField(default="PENDING", max_length=100),
        ),
    ]
