# Generated by Django 4.2.7 on 2023-11-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HodDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_number", models.IntegerField()),
                ("department", models.CharField(max_length=10)),
            ],
        ),
    ]
